services:
  - name: rdbms
    type: database
    env:
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
      - key: MYSQL_DATABASE
        value: nathabit_db
      - key: MYSQL_USER
        value: nathabit_db_user
      - key: nathabit@123
        generateValue: true

  - name: api-gateway
    type: web
    buildCommand: docker-compose build api-gateway
    startCommand: docker-compose up api-gateway
    healthCheckPath: / # Adjust this according to your application

  - name: auth-service
    type: web
    buildCommand: docker-compose build auth-service
    startCommand: docker-compose up auth-service
    healthCheckPath: / # Adjust this according to your application
    env:
      - key: ENV
        value: ${ENV}

  - name: api-service
    type: web
    buildCommand: docker-compose build api-service
    startCommand: docker-compose up api-service
    healthCheckPath: / # Adjust this according to your application
    env:
      - key: ENV
        value: ${ENV}

  - name: movie-service
    type: web
    buildCommand: docker-compose build movie-service
    startCommand: docker-compose up movie-service
    healthCheckPath: / # Adjust this according to your application
    env:
      - key: ENV
        value: ${ENV}

  - name: user-service
    type: web
    buildCommand: docker-compose build user-service
    startCommand: docker-compose up user-service
    healthCheckPath: / # Adjust this according to your application
    env:
      - key: ENV
        value: ${ENV}

  - name: frontend
    type: web
    buildCommand: docker-compose build frontend
    startCommand: docker-compose up frontend
    healthCheckPath: / # Adjust this according to your application

databases:
  - name: rdbms
    memory: 512M # Adjust based on your database requirements
    env:
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
      - key: MYSQL_DATABASE
        value: nathabit_db # Provide your MySQL database name
      - key: MYSQL_USER
        value: nathabit_db_user # Provide your MySQL user
      - key: nathabit@123
        generateValue: true
